### ISSUE TITLE
Question: Pass a parameter to an import?

### ISSUE THREAD

**Issue by viniciusgama** [pcreux/csv-importer#95]
Is it possible to pass a parameter to an import so I can use that to find or create a record when setting a value for a column? Something like the following:
```ruby
class ImportUserCsv
  include CsvImporter

  model User
  column :name
  column :team, to: -> (team_name, organization_id) { Team.find_or_create_by!(name: team_name, organization_id: organization_id) }
end

import = ImportTasksCsv.new(file: my_file)

import.run!(organization_id: organization_id)
```

As you can see, the organization would be something that would be set at runtime and will not be present in the csv. It will be set depending on the organization of the logged in user that is requesting the import.

**Comment by pcreux** [comment]
I haven't tested it myself, but you might be able to define that column at runtime.

See: https://github.com/pcreux/csv-importer#overwrite-configuration-at-runtime

**Comment by sshaw** [comment]
I think passing an arg to `run` is a bit more flexible as expecting a `model` that's scoped to an organization is not always practical.

In the case I'm dealing with I need to [create an association based on the values of multiple CSV columns](https://github.com/pcreux/csv-importer/issues/28#issuecomment-741600934). This association must be scoped to a `User`. 

The association based on the values of multiple CSV columns _seems_ possible with something like this:

```rb
class OrgProxy
  attr_accessor :name
  attr_accessor :relation_column_1
  attr_accessor :relation_column_2
  attr_accessor :relation_column_x
   
  def self.find_by(*argz)
    org = Org.find_by(*argz)
    return unless org
    OrgProxy.new(:name => org.name)
  end

  def save
    org = Org.new(:name => name)
    org.relation.find_or_initialize_by(:column_1 => relation_column_1, :column_2 => relation_column_2) do |record|
      record.column_x = relation_column_x
    end
    org.save! # or whatever
  end
end

class Importer
  include CSVImporter

  model OrgProxy

  # column mapping
end
```

Okay, not tested –just evaluating this lib at a high-level– but appears it to be a possible solution.

**But**, then I want to scope it to a `User`'s `Org`. How to do that? You need an `OrgProxy` with class methods scoped to the given `User` instance.

What are the options?

```rb
Class.new(OrgProxy) do 
  # dynamic class scoped to User instance
end
```

```rb
class OrgProxy
  def self.current_user
     Thread.current[:current_user]
  end

  def self.current_user=(user)
     Thread.current[:current_user] = user
  end

  def self.find_by(*argz)
    current_user.orgs.find_by(*args)
    # etc...
  end
end
```

```rb
class OrgProxy < Org
  attr_accessor :relation_column_1
  # etc...
end
````

This last case wont work since `user.orgs.new`, etc... will return `Org` not `OrgProxy`


These aren't great options. Maybe I'm missing something? Otherwise it doesn't seem doable :(

**Comment by pcreux** [comment]
Hello @sshaw ,

I believe that you can use an `after_build` block for the first use case and pass the scope at runtime for the second one (`model user.orgs`).

**Comment by sshaw** [comment]
Hi, it's been a few days since my head was in this problem but I don't think would since the `relation` from `current_user.orgs` needs to be looked up based on several columns in the spreadsheet. 

It appears the only way to do this is in `after_build` but to look the association(s) up in `after_build` we need to store the lookup columns values in the importer (or more specifically, on its model). 

To store the values in the importer its `model` must respond to these methods, right? But they do not. Hence my idea for a proxy class. But with the proxy it's not that nice since we need a one-off class with class methods scoped to the org. See my example above. 

Does that make sense?

**Comment by pcreux** [comment]
I believe that the dynamic scope and dynamic association makes your use case too far from what CSVImporter was built for. 😕

**Comment by sshaw** [comment]
Yes so it seems but... if, as Vinicius suggested `run` accepted arguments, one can use the `OrgProxy` approach and then scope the instances based off the ID passed to `run`. No need worry about `model` and its required interface.
